# Generated by Django 5.2.17 on 2026-10-03 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "متن کوتاه"),
                            ("textarea", "متن بلند"),
                            ("number", "عدد"),
                            ("select", "انتخابی"),
                            ("checkbox", "چندانتخابی"),
                            ("rating", "امتیاز"),
                            ("date", "تاریخ"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("value_date", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("value_text", models.TextField(blank=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="forms.field"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="options", to="forms.field"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="selected_options", to="forms.answer"
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answer_links", to="forms.fieldoption"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "عمومی"), ("private", "خصوصی")], default="public", max_length=10
                    ),
                ),
                ("access_password", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("accepts_responses_until", models.DateTimeField(blank=True, null=True)),
                ("enforce_field_order", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forms",
                        to="categories.category",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="forms", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="field",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="forms.form"
            ),
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(blank=True, db_index=True, max_length=64)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="forms.form"
                    ),
                ),
            ],
        ),
    ]
