# Generated by Django 5.2.17 on 2026-10-03 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        ("processes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="process_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="processes.processrun",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="respondent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="forms.submission"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fieldoption",
            unique_together={("field", "value")},
        ),
        migrations.AlterUniqueTogether(
            name="answeroption",
            unique_together={("answer", "option")},
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(fields=["form", "order"], name="forms_field_form_id_625e6a_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["form", "created_at"], name="forms_submi_form_id_7661c6_idx"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["field", "value_number"], name="forms_answe_field_i_50f831_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("submission", "field")},
        ),
    ]
