# Generated by Django 5.2.17 on 2026-10-03 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(blank=True, choices=[("form", "فرم"), ("process", "فرایند")], max_length=10),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "period",
                    models.CharField(
                        choices=[("weekly", "هفتگی"), ("monthly", "ماهانه")], default="weekly", max_length=10
                    ),
                ),
                (
                    "delivery",
                    models.CharField(
                        choices=[("email", "ایمیل"), ("webhook", "ارسال به API")], default="email", max_length=10
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("webhook_url", models.URLField(blank=True)),
                ("secret", models.CharField(blank=True, max_length=128)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_success", models.BooleanField(default=False)),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="reports.reportschedule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VisitCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_type", models.CharField(choices=[("form", "فرم"), ("process", "فرایند")], max_length=10)),
                ("object_id", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [models.Index(fields=["target_type", "object_id"], name="reports_vis_target__c3dfdd_idx")],
                "unique_together": {("target_type", "object_id", "date")},
            },
        ),
    ]
